# Template document for helix color schemes
# See also: https://docs.helix-editor.com/themes.html
#
# NOTE: Keys default to the most specific parent value.
#       e.g ui.cursor.primary > ui.cursor > ui



# GENERAL ==============================

warning = { fg = "red-one" } # Editor warnings.
error = { fg = "red-one" } # Editor errors, like mis-typing a command.
info = { fg = "light-one", bg = "red-one" } # Contextual info in diagnostic messages (LSP).
hint = { fg = "light-one", bg = "red-one" } # Code diagnostics hints (LSP).
diagnostic = { fg = "light-one", bg = "red-one" } # Code diagnostics in editing area (LSP).

# UI ==============================
# For styling helix itself.

'ui.background' = "dark-five"  # Default background color.
'ui.window' = { } # Window border between splits.
'ui.gutter' = { bg = "dark-fourth"} # Left gutter for diagnostics and breakpoints.

'ui.text' = "light-one" # Default text color.
'ui.text.focus' = { } # Selection highlight in buffer-picker or file-picker.
'ui.text.info' = { } # Info popup contents (space mode menu).

'ui.cursor' = { bg = "light-five" } # Fallback cursor colour, non-primary cursors when there are multiple (shift-c).
'ui.cursor.primary' = { bg = "light-five" } # The primary cursor when there are multiple (shift-c).
'ui.cursor.insert' = { bg = "purple-one" } # The cursor in insert mode (i).
'ui.cursor.select' = { } # The cursor in select mode (v).
'ui.cursor.match' = { bg = "dark-one" } # The matching parentheses of that under the cursor.

'ui.selection' = { bg = "blue-five" } # All currently selected text.
'ui.selection.primary' = { bg = "blue-five" } # The primary selection when there are multiple.

'ui.linenr' = { fg = "light-one" } # Line numbers.
'ui.linenr.selected' = { fg = "dark-five", bg = "light-three" } # Current line number.

'ui.virtual' = { } # Namespace for additions to the editing area.
'ui.virtual.ruler' = { } # Vertical rulers (colored columns in editing area).
'ui.virtual.whitespace' = { } # Whitespace markers in editing area.

'ui.statusline' = { fg = "light-one", bg = "dark-fourth" } # Status line.
'ui.statusline.active' = { } # Status line in focused windows.
'ui.statusline.inactive' = { } # Status line in unfocused windows.
"ui.statusline.normal" = { } # Statusline mode during normal mode (only if editor.color-modes is enabled)
"ui.statusline.insert" = { } # Statusline mode during insert mode (only if editor.color-modes is enabled)
"ui.statusline.select" = { } # Statusline mode during select mode (only if editor.color-modes is enabled)

'ui.help' = { fg = "light-one", bg = "dark-fourth" } # `:command` descriptions above the command line.

'ui.highlight' = { } # selected contents of symbol pickers (spc-s, spc-S) and current line in buffer picker (spc-b).

'ui.menu' = { fg = "light-one", bg = "dark-fourth" } # Autocomplete menu.
'ui.menu.selected' = { fg = "light-one", bg = "orange-five" } # Selected autocomplete item.

'ui.popup' = { } # Documentation popups (space-k).
'ui.popup.info' = { } # Info popups box (space mode menu).


# SYNTAX HIGHLIGHTING ==============================
# All the keys here are Treesitter scopes.

'property' = { } # Regex group names.
'special' = { } # Special symbols e.g `?` in Rust, `...` in Hare.
'attribute' = { } # Class attributes, html tag attributes.

'type' = { } # Variable type, like integer or string, including program defined classes, structs etc..
'type.builtin' = { } # Primitive types of the language (string, int, float).
'type.enum.variant' = { } # A variant of an enum.

'constructor' = { } # Constructor method for a class or struct.

'constant' = { fg = "purple-one" } # Constant value
'constant.builtin' = { } # Special constants like `true`, `false`, `none`, etc.
'constant.builtin.boolean' = { } # True or False.
'constant.character' = { } # Constant of character type.
'constant.character.escape' = { } # escape codes like \n.
'constant.numeric'  = { } # constant integer or float value.
'constant.numeric.integer' = { } # constant integer value.
'constant.numeric.float' = { } # constant float value.

'string' = { fg = "green-one" } # String literal.
# 'string.regexp' = { } # Regular expression literal.
'string.special' = { fg = "orange-five" } # Strings containing a path, URL, etc.
# 'string.special.path' = { } # String containing a file path.
# 'string.special.url' = { } # String containing a web URL.
# 'string.special.symbol' = { } # Erlang/Elixir atoms, Ruby symbols, Clojure keywords.

'comment' = { fg = "yellow-three" } # This is a comment.
# 'comment.line' = { } # Line comments, like this.
# 'comment.block' = { } # Block comments, like /* this */ in some languages.
# 'comment.block.documentation' = { } # Doc comments, e.g '///' in rust.

'variable' = { } # Variable names.
'variable.builtin' = { } # Language reserved variables: `this`, `self`, `super`, etc.
'variable.parameter' = { } # Function parameters.
'variable.other.member' = { } # Fields of composite data types (e.g. structs, unions).

'label' = { } # Loop labels, among other things.

'punctuation' = { } # Any punctuation symbol.
'punctuation.delimiter' = { } # Commas, colons or other delimiter depending on the language.
'punctuation.bracket' = { } # Parentheses, angle brackets, etc.

'keyword' = { } # Language reserved keywords.
'keyword.control' = { } # Control keywords.
'keyword.control.conditional' = { } # `if`, `else`, `elif`.
'keyword.control.repeat' = { } # `for`, `while`, `loop`.
'keyword.control.import' = { } # `import`, `export` `use`.
'keyword.control.return' = { } # `return` in most languages.
'keyword.control.exception' = { } # `try`, `catch`, `raise`/`throw` and related.
'keyword.operator' = { } # `or`, `and`, `in`.
'keyword.directive' = { } # Preprocessor directives (#if in C...).
'keyword.function' = { } # The keyword to define a function: 'def', 'fun', 'fn'.

'operator' = { } # Logical, mathematical, and other operators.

'function' = { fg = "blue-three" }
'function.builtin' = { fg = "light-one" }
'function.method' = { fg = "light-one" } # Class / Struct methods.
'function.macro' = { fg = "light-one" }
# 'function.special' = { } # Preprocessor function in C.

'tag' = { } # As in <body> for html, css tags.
'tag.error' = { } # Erroneous closing html tags.

'namespace' = { } # Namespace or module identifier.


# Markup ==============================
# Colors for markup languages, like Markdown or XML.

'markup.heading.1' = { } # Markdown heading 1 color.
'markup.heading.2' = { } # Markdown heading 2 color.
'markup.heading.3' = { } # Markdown heading 3 color.
'markup.heading.4' = { } # Markdown heading 4 color.
'markup.heading.5' = { } # Markdown heading 5 color.
'markup.heading.6' = { } # Markdown heading 6 color.
'markup.heading.marker' = { } # Hashtag color on Markdown headings.

'markup.list' = { }
'markup.list.numbered' = { } # Numbered list.
'markup.list.unnumbered' = { } # Bullet point list.

'markup.bold' = { } # Bold text.
'markup.italic' = { } # Italicised text.

'markup.link' = { }
'markup.link.url' = { } # Urls pointed to by links.
'markup.link.label' = { } # Non-URL link references.
'markup.link.text' = { } # URL and image descriptions in links.

'markup.quote' = { } # `> Quotes` in Markdown.


# Markup - Interface ==============================
# "These scopes are used for theming the editor interface."

'markup.normal' = { }
'markup.normal.completion' = { } # For completion doc popup ui.
'markup.normal.raw' = { } # For hover popup ui.

'markup.heading.completion' = { } # Headings for completion doc popup ui.
'markup.heading.raw' = { } # Headings for hover popup ui.

'markup.raw' = { } # Code block in Markdown.
'markup.raw.block' = { } # Multiline (```) codeblock in Markdown.
'markup.raw.inline' = { } # `Inline code block` in Markdown.
'markup.raw.inline.completion' = { } # ?
'markup.raw.inline.hover' = { } # ?

# Diff ==============================
# Version control changes.

'diff.plus' = { fg = "green-five" } # Additions.
'diff.minus' = { fg = "red-five" } # Deletions.
'diff.delta' = { } # Modifications.
'diff.delta.moved' = { } # Renamed or moved files.


[palette] # Define your custom colors here.
# GNOME color palette
# https://developer.gnome.org/hig/reference/palette.html
light-one = "#FFFFFF"
light-three = "#DEDDDA"
light-five = "#9A9996"

dark-one = "#77767B"
dark-two = "#5E5C64"
dark-three = "#3D3846"
dark-fourth = "#241F31"
dark-five = "#000000"

blue-one = "#99C1F1"
blue-three = "#3584E4"
blue-five = "#1A5FB4"

green-one = "#8FF0A4"
green-three = "#33D17A"
green-five = "#26A269"

yellow-one = "#F9F06B"
yellow-three = "#F6D32D"
yellow-five = "#E5A50A"

orange-one = "#FFBE6F"
orange-three = "#FF7800"
orange-five = "#C64600"

red-one = "#F66151"
red-three = "#E01B24"
red-five = "#A51D2D"

purple-one = "#DC8ADD"
purle-three = "#9141AC"
purple-five = "#613583"

brown-one = "#CDAB8F"
brown-three = "#986A44"
brown-five = "#63452C"
